### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by nick007007** [Clansty/nuist-goout-v2#1]
小姐姐可以教下怎么用吗，校友学数学的不懂前端orz
怎么在手机上打开这个页面
怎么设置姓名
二维码颜色咋是蓝的
有没有进校页面

**Comment by clansty** [comment]
https://github.com/Clansty/nuist-goout-v2/blob/d0581c66c00d098b662657d3558a2edb0d2017b0/out.html#L769-L781

**Comment by nick007007** [comment]
参数都写在url后面是吧，请问学院名称的参数名是啥，没找到orz
